---
spring:
 cloud:
  config:
   server:
    git:
     uri: https://github.com/alexey-slepov/study-springcloud-intro
     searchPaths: config

eureka:
 client:
  registerWithEureka: false
  fetchRegistry: false

server:
 port: 5500